from colorama import *
import time

print (Style.BRIGHT + "Backgrounds: " +  Style.RESET_ALL)
time.sleep(3)
print (Back.BLACK + Fore.WHITE + "black  ")
time.sleep(1)
print (Back.RED + Fore.WHITE + "red    ")
time.sleep(1)
print (Back.GREEN + Fore.WHITE + "green  ")
time.sleep(1)
print (Back.YELLOW + Fore.WHITE + "yellow ")
time.sleep(1)
print (Back.BLUE + Fore.WHITE + "blue   ")
time.sleep(1)
print (Back.MAGENTA + Fore.WHITE + "magenta")
time.sleep(1)
print (Back.CYAN + Fore.WHITE + "cyan   ")
time.sleep(1)
print (Back.WHITE + Fore.WHITE + "white  ")
print (Back.RESET + Fore.RESET)
time.sleep(2)

print (Style.BRIGHT + "Foregrounds: " + Style.RESET_ALL)
time.sleep(3)
print (Fore.BLACK + "black  ")
time.sleep(1)
print (Fore.RED + "red    ")
time.sleep(1)
print (Fore.GREEN + "green  ")
time.sleep(1)
print (Fore.YELLOW + "yellow ")
time.sleep(1)
print (Fore.BLUE + "blue   ")
time.sleep(1)
print (Fore.MAGENTA + "magenta")
time.sleep(1)
print (Fore.CYAN + "cyan   ")
time.sleep(1)
print (Fore.WHITE + "white  ")

